[package]
name = "trade_engine_rust"
version = "0.1.0"
authors = ["Nathan Bruer <thegreatall@gmail.com>"]
publish = false

[[bin]]
name = "tradeengine"
path = "src/main.rs"

[dependencies]
libtradeengine = {path = "src/libtradeengine", test = true}
quick-protobuf = "0.6.3"
rand = "0.3"
